//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiRite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioInputChannel_1 {
            get {
                return ((uint)(this["AudioInputChannel_1"]));
            }
            set {
                this["AudioInputChannel_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioOutputChannel_2 {
            get {
                return ((uint)(this["AudioOutputChannel_2"]));
            }
            set {
                this["AudioOutputChannel_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Decode_ndepth {
            get {
                return ((int)(this["Decode_ndepth"]));
            }
            set {
                this["Decode_ndepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Decode_lft8apon {
            get {
                return ((bool)(this["Decode_lft8apon"]));
            }
            set {
                this["Decode_lft8apon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioInputChannel_2 {
            get {
                return ((uint)(this["AudioInputChannel_2"]));
            }
            set {
                this["AudioInputChannel_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioOutputChannel_1 {
            get {
                return ((uint)(this["AudioOutputChannel_1"]));
            }
            set {
                this["AudioOutputChannel_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioInputChannel_3 {
            get {
                return ((uint)(this["AudioInputChannel_3"]));
            }
            set {
                this["AudioInputChannel_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioOutputChannel_3 {
            get {
                return ((uint)(this["AudioOutputChannel_3"]));
            }
            set {
                this["AudioOutputChannel_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioInputChannel_4 {
            get {
                return ((uint)(this["AudioInputChannel_4"]));
            }
            set {
                this["AudioInputChannel_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioOutputChannel_4 {
            get {
                return ((uint)(this["AudioOutputChannel_4"]));
            }
            set {
                this["AudioOutputChannel_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioInputDevice_1 {
            get {
                return ((string)(this["AudioInputDevice_1"]));
            }
            set {
                this["AudioInputDevice_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioInputDevice_2 {
            get {
                return ((string)(this["AudioInputDevice_2"]));
            }
            set {
                this["AudioInputDevice_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioInputDevice_3 {
            get {
                return ((string)(this["AudioInputDevice_3"]));
            }
            set {
                this["AudioInputDevice_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioInputDevice_4 {
            get {
                return ((string)(this["AudioInputDevice_4"]));
            }
            set {
                this["AudioInputDevice_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioOutputDevice_1 {
            get {
                return ((string)(this["AudioOutputDevice_1"]));
            }
            set {
                this["AudioOutputDevice_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioOutputDevice_2 {
            get {
                return ((string)(this["AudioOutputDevice_2"]));
            }
            set {
                this["AudioOutputDevice_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioOutputDevice_3 {
            get {
                return ((string)(this["AudioOutputDevice_3"]));
            }
            set {
                this["AudioOutputDevice_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioOutputDevice_4 {
            get {
                return ((string)(this["AudioOutputDevice_4"]));
            }
            set {
                this["AudioOutputDevice_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallUsed {
            get {
                return ((string)(this["CallUsed"]));
            }
            set {
                this["CallUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyGrid {
            get {
                return ((string)(this["MyGrid"]));
            }
            set {
                this["MyGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ContestExchange {
            get {
                return ((int)(this["ContestExchange"]));
            }
            set {
                this["ContestExchange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultAcknowlegement {
            get {
                return ((int)(this["DefaultAcknowlegement"]));
            }
            set {
                this["DefaultAcknowlegement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SavedVersion {
            get {
                return ((int)(this["SavedVersion"]));
            }
            set {
                this["SavedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenu {
            get {
                return ((bool)(this["ShowMenu"]));
            }
            set {
                this["ShowMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("245, 250, 250")]
        public global::System.Drawing.Color Background {
            get {
                return ((global::System.Drawing.Color)(this["Background"]));
            }
            set {
                this["Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("235, 245, 240")]
        public global::System.Drawing.Color TxBackground {
            get {
                return ((global::System.Drawing.Color)(this["TxBackground"]));
            }
            set {
                this["TxBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxUnansweredMinutes {
            get {
                return ((int)(this["MaxUnansweredMinutes"]));
            }
            set {
                this["MaxUnansweredMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lucida Console, 9pt")]
        public global::System.Drawing.Font FixedFont {
            get {
                return ((global::System.Drawing.Font)(this["FixedFont"]));
            }
            set {
                this["FixedFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeftClickIsMyTx {
            get {
                return ((bool)(this["LeftClickIsMyTx"]));
            }
            set {
                this["LeftClickIsMyTx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CQ")]
        public string CQmessage {
            get {
                return ((string)(this["CQmessage"]));
            }
            set {
                this["CQmessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContestMessageToSend {
            get {
                return ((string)(this["ContestMessageToSend"]));
            }
            set {
                this["ContestMessageToSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort OnLoggedAcknowedgeMessage {
            get {
                return ((ushort)(this["OnLoggedAcknowedgeMessage"]));
            }
            set {
                this["OnLoggedAcknowedgeMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCalcNextToSend {
            get {
                return ((bool)(this["ShowCalcNextToSend"]));
            }
            set {
                this["ShowCalcNextToSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public ushort ReactivateQSOTimerMinutes {
            get {
                return ((ushort)(this["ReactivateQSOTimerMinutes"]));
            }
            set {
                this["ReactivateQSOTimerMinutes"] = value;
            }
        }
    }
}
